/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Util.UserServiceUtil;
import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;

import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) {
        System.out.println("Running ticket booking system");
        Scanner scanner = new Scanner(System.in);
        int option=0;
        UserBookingService userBookingService;
        try{
            userBookingService= new UserBookingService();
        }catch (IOException e){
            System.out.println("There is something wrong");
        }
        while(option!=7) {
            System.out.println("Choose an option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch booking");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the app");
            option=scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("Enter Username to signup");
                    String nameToSignup= scanner.next();
                    System.out.println("Enter password to signup");
                    String passwordToSignup=scanner.next();
                    User usertoSignup= new User(nameToSignup,passwordToSignup,
                            UserServiceUtil.hashPassword(passwordToSignup),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    UserBookingService.signup(usertoSignup);
                    break;
                case 2:
                    System.out.println("Enter Username to login");
                    String nameToLogin= scanner.next();
                    System.out.println("Enter password to login");
                    String passwordToLogin= scanner.next();
                    User usertoLogin= new User(nameToLogin,passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin),
                            new ArrayList<>(),UUID.randomUUID().toString());
                    try {
                        userBookingService=new UserBookingService(usertoLogin);
                    }catch (IOException e){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookig2");
                    User fetch= new User();
                    UserBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String src= scanner.next();
                    System.out.println("Type your destination station");
                    String des=scanner.next();
                    List<Train>trains=UserBookingService.getTrain(source,dest);
                    int index=1;
                    for(Train t:trains){
                        System.out.println(index+"Train Id : "+t.getTrains());
                        for(Map.Entry<String,String>entry:t.getStationTimes().entrySet()){
                            System.out.println("Station: "+entry.getKey()+"Time: "+entry.getValue());
                        }
                    }
            }

        }
    }
}
